[datadir.paths]
# You may override the specific job results directory with logs_dir
logs_dir = /mnt/local/results

[runner.output]
# Whether to display colored output in terminals that support it
colored = True
# Whether to force colored output to non-tty outputs (e.g. log files)
# Allowed values: auto, always, never
color = always
